AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-sam-scratchpad
  
Globals:
  Function:
    Timeout: 3

Parameters:
  AppName:
    Type: String
    Default: aws-sam-scratchpad
  Stage:
    Type: String
    Default: development

Resources:
  ApiAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: 
            Fn::Sub: ${AppName}-api-access-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - Fn::Sub: ${PostToDynamoFunction.Arn}
                  - Fn::Sub: ${FetchDynamoFunction.Arn}

  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name:
        Fn::Sub: ${AppName}-api-${Stage}
      StageName: !Ref Stage 
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: application/src/service-layer/swagger.yaml
  
  ExampleTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: example-table
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  PostToDynamoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: application/src/service-layer/controllers/
      Handler: ExampleController.createItem
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Policies:
       - DynamoDBCrudPolicy:
          TableName: !Ref ExampleTable
      Environment:
        Variables:
          TABLE_NAME: !Ref ExampleTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - ExampleController.ts

  FetchDynamoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: application/src/service-layer/controllers/
      Handler: ExampleController.getItem
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Policies:
       - DynamoDBCrudPolicy:
          TableName: !Ref ExampleTable
      Environment:
        Variables:
          TABLE_NAME: !Ref ExampleTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - ExampleController.ts


