name: Pipeline

on:
  push:
    branches:
      - '**'
jobs:
  test:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
      - run: npm install
        working-directory: ./application
      - run: npm run build --if-present
        working-directory: ./application
      - run: npm test
        working-directory: ./application